name: bexit_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  awesome_dio_interceptor: 0.0.2+4
  retrofit: 3.3.1
  mockito: 5.3.2
  awesome_dialog: 3.0.2
  flutter_spinkit: 5.1.0
  libphonenumber: 2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  retrofit_generator: 4.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

